{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "439e8db5",
   "metadata": {},
   "source": [
    "import pandas as pd\n",
    "import re\n",
    "from collections import Counter\n",
    "from math import sqrt\n",
    "from pathlib import Path\n",
    "\n",
    "MOVIE_FILE = Path(\"ml-32m/movies.csv\")\n",
    "\n",
    "\n",
    "def clean_text(text: str) -> str:\n",
    "    \"\"\"Lowercase titles and remove punctuation for token matching.\"\"\"\n",
    "    text = re.sub(r\"\\(\\d{4}\\)$\", \"\", str(text))\n",
    "    text = re.sub(r\"[^a-z0-9 ]\", \" \", text.lower())\n",
    "    return re.sub(r\"\\s+\", \" \", text).strip()\n",
    "\n",
    "\n",
    "def build_token_counts(title: str) -> Counter:\n",
    "    return Counter(clean_text(title).split())\n",
    "\n",
    "\n",
    "def cosine_similarity(a: Counter, b: Counter) -> float:\n",
    "    intersection = set(a) & set(b)\n",
    "    numerator = sum(a[token] * b[token] for token in intersection)\n",
    "    norm_a = sqrt(sum(value * value for value in a.values()))\n",
    "    norm_b = sqrt(sum(value * value for value in b.values()))\n",
    "    return numerator / (norm_a * norm_b) if norm_a and norm_b else 0.0\n",
    "\n",
    "\n",
    "def load_movie_titles(path: Path = MOVIE_FILE) -> pd.DataFrame:\n",
    "    movies = pd.read_csv(path)\n",
    "    if \"movieId\" in movies.columns:\n",
    "        movies = movies.rename(columns={\"movieId\": \"item_id\"})\n",
    "    movies[\"clean_title\"] = movies[\"title\"].apply(clean_text)\n",
    "    movies[\"token_counts\"] = movies[\"title\"].apply(build_token_counts)\n",
    "    return movies\n",
    "\n",
    "\n",
    "def recommend_similar_movies(query: str, movies: pd.DataFrame, top_n: int = 10) -> pd.DataFrame:\n",
    "    query_tokens = build_token_counts(query)\n",
    "    scores = []\n",
    "\n",
    "    for _, row in movies.iterrows():\n",
    "        score = cosine_similarity(query_tokens, row[\"token_counts\"])\n",
    "        if score > 0:\n",
    "            scores.append((row[\"item_id\"], row[\"title\"], score))\n",
    "\n",
    "    recommendations = sorted(scores, key=lambda item: item[2], reverse=True)\n",
    "    return pd.DataFrame(recommendations, columns=[\"item_id\", \"title\", \"score\"]).head(top_n)\n",
    "\n",
    "\n",
    "def recommend_for_user(liked_titles: list[str], movies: pd.DataFrame, top_n: int = 10) -> pd.DataFrame:\n",
    "    aggregated = Counter()\n",
    "    for title in liked_titles:\n",
    "        aggregated.update(build_token_counts(title))\n",
    "\n",
    "    scores = []\n",
    "    for _, row in movies.iterrows():\n",
    "        if row[\"title\"] in liked_titles:\n",
    "            continue\n",
    "        score = cosine_similarity(aggregated, row[\"token_counts\"])\n",
    "        if score > 0:\n",
    "            scores.append((row[\"item_id\"], row[\"title\"], score))\n",
    "\n",
    "    recommendations = sorted(scores, key=lambda item: item[2], reverse=True)\n",
    "    return pd.DataFrame(recommendations, columns=[\"item_id\", \"title\", \"score\"]).head(top_n)\n",
    "\n",
    "\n",
    "def main() -> None:\n",
    "    movies = load_movie_titles()\n",
    "    print(f\"Loaded {len(movies)} movies from {MOVIE_FILE.name}\")\n",
    "    print(\"\\nTop recommendations similar to 'Toy Story':\")\n",
    "    print(recommend_similar_movies(\"Toy Story\", movies, top_n=8).to_string(index=False))\n",
    "    print(\"\\nRecommendations for a user who likes Toy Story and GoldenEye:\")\n",
    "    print(recommend_for_user([\"Toy Story (1995)\", \"GoldenEye (1995)\"], movies, top_n=8).to_string(index=False))\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "43adddea",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
